var prostokat1 = Prostokat(a: 5.5, b: 4.0)
var prostokat2 = Prostokat(a: 6.0, b: 15.0)
prostokat1.wyswietl()
print("Pole prostokata jest rowne \(prostokat1.pole())")
print("Obwod prostokata jest rowny \(prostokat1.obw())")
prostokat2.wyswietl()
print("Pole prostokata jest rowne \(prostokat2.pole())")
print("Obwod prostokata jest rowny \(prostokat2.obw())")
var prostopadloscian1 = Prostopadloscian(h: 3.5, a:5.0, b:4.0)
var prostopadloscian2 = Prostopadloscian(h: 7.0, a:3.5, b:6.4)
prostopadloscian1.wyswietl()
print("Pole calkowite prostopadloscianu jest rowne \(prostopadloscian1.polecalkowite())")
print("Suma krawedzi prostopadloscianu jest rowna \(prostopadloscian1.sumakrawedzi())")
print("Objetosc prostopadloscianu jest rowna \(prostopadloscian1.objProst())")

prostopadloscian2.wyswietl()
print("Pole calkowite prostopadloscianu jest rowne \(prostopadloscian2.polecalkowite())")
print("Suma krawedzi prostopadloscianu jest rowna \(prostopadloscian2.sumakrawedzi())")
print("Objetosc prostopadloscianu jest rowna \(prostopadloscian2.objProst())")
